name: 516_analyses
channels:
  - conda-forge
  - bioconda

dependencies:
  - python
  - r-base=4.3
  - r-irkernel
  - r-rmarkdown
  - r-knitr

  # core R packages
  - r-tidyverse
  - r-stringr
  - r-scales
  - r-rcolorbrewer
  - r-pheatmap
  - r-gridextra
  - r-cowplot
  - r-ggforce
  - r-vegan
  - r-zcompositions

  # bioconductor / microbiome stack
  - bioconductor-phyloseq
  - bioconductor-biomformat
  - bioconductor-rhdf5
  - bioconductor-microbiome
